version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - local
  characters-5e:
    container_name: svc
    restart: always
    build:
      context: .
    environment:
      DB_URL: postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - 8080:8080
    networks:
      - local
    depends_on:
      - db

networks:
  local: